// <auto-generated />
using System;
using Banco.WebApi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banco.WebApi.Infrastructure.Migrations
{
    [DbContext(typeof(BancoDbContext))]
    partial class BancoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Banco.WebApi.Entity.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<int>("Identificacion")
                        .HasColumnType("int");

                    b.HasKey("ClienteId")
                        .HasName("PK__Cliente__71ABD087F54D3F3C");

                    b.HasIndex("Identificacion");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("Banco.WebApi.Entity.Cuenta", b =>
                {
                    b.Property<int>("NumeroCuenta")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.HasKey("NumeroCuenta")
                        .HasName("PK__Cuenta__E039507A14A4C2DB");

                    b.HasIndex("ClienteId");

                    b.ToTable("Cuenta");
                });

            modelBuilder.Entity("Banco.WebApi.Entity.Movimiento", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimientoId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("NumeroCuenta")
                        .HasColumnType("int");

                    b.Property<decimal?>("Saldo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("SaldoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MovimientoId")
                        .HasName("PK__Movimien__BF923C2C3B6FE0F3");

                    b.HasIndex("NumeroCuenta");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("Banco.WebApi.Entity.Persona", b =>
                {
                    b.Property<int>("Identificacion")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Identificacion")
                        .HasName("PK__Persona__D6F931E4C38092D6");

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("Banco.WebApi.Entity.Cliente", b =>
                {
                    b.HasOne("Banco.WebApi.Entity.Persona", "IdentificacionNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("Identificacion")
                        .IsRequired()
                        .HasConstraintName("FK__Cliente__Identif__398D8EEE");

                    b.Navigation("IdentificacionNavigation");
                });

            modelBuilder.Entity("Banco.WebApi.Entity.Cuenta", b =>
                {
                    b.HasOne("Banco.WebApi.Entity.Cliente", "Cliente")
                        .WithMany("Cuenta")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK__Cuenta__ClienteI__3C69FB99");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Banco.WebApi.Entity.Movimiento", b =>
                {
                    b.HasOne("Banco.WebApi.Entity.Cuenta", "NumeroCuentaNavigation")
                        .WithMany("Movimientos")
                        .HasForeignKey("NumeroCuenta")
                        .IsRequired()
                        .HasConstraintName("FK__Movimient__Numer__3F466844");

                    b.Navigation("NumeroCuentaNavigation");
                });

            modelBuilder.Entity("Banco.WebApi.Entity.Cliente", b =>
                {
                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("Banco.WebApi.Entity.Cuenta", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Banco.WebApi.Entity.Persona", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
